CREATE TABLE ihs14_rns_upload_files (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catid int NOT NULL DEFAULT '0',
  filename varchar(350) DEFAULT NULL,
  filepath varchar(600) DEFAULT NULL,
  created timestamp DEFAULT NULL,
  created_by int DEFAULT NULL,
  modified timestamp DEFAULT NULL,
  modified_by int DEFAULT NULL,
  published int DEFAULT NULL
);